use std::fs;
use std::path::Path;

fn collect_yaml_files(dir: &Path) -> Vec<String> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |e| e == "yaml" || e == "yml") {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    files.push(name.to_string());
                }
            }
        }
    }
    files.sort();
    files
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let tasks_dir = Path::new(&manifest_dir).join("tasks");
    let blueprints_dir = Path::new(&manifest_dir).join("blueprints");
    let profiles_dir = Path::new(&manifest_dir).join("apparmor-profiles");

    let task_files = collect_yaml_files(&tasks_dir);
    let blueprint_files = collect_yaml_files(&blueprints_dir);
    let profile_files = collect_yaml_files(&profiles_dir);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    code.push_str("pub const BUILTIN_TASK_YAMLS: &[&str] = &[\n");
    for file in &task_files {
        code.push_str(&format!("    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/tasks/{}\")),\n", file));
    }
    code.push_str("];\n\n");

    code.push_str("pub const BUILTIN_BLUEPRINT_YAMLS: &[&str] = &[\n");
    for file in &blueprint_files {
        code.push_str(&format!("    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/blueprints/{}\")),\n", file));
    }
    code.push_str("];\n\n");

    code.push_str("pub const BUILTIN_PROFILE_YAMLS: &[&str] = &[\n");
    for file in &profile_files {
        code.push_str(&format!("    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/apparmor-profiles/{}\")),\n", file));
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).expect("Failed to write embedded.rs");

    // Re-run build script if YAML files change
    println!("cargo:rerun-if-changed=tasks/");
    println!("cargo:rerun-if-changed=blueprints/");
    println!("cargo:rerun-if-changed=apparmor-profiles/");

    tauri_build::build()
}
